
services:
  transactionservice1:
    build:
      context: .
      dockerfile: TransactionService/Dockerfile
    depends_on:
      - sqlserver
      - redis
    entrypoint: ["dotnet", "TransactionService.dll"]
    ports:
      - "5001:8080"

  transactionservice2:
    build:
      context: .
      dockerfile: TransactionService/Dockerfile
    depends_on:
      - sqlserver
      - redis
    entrypoint: ["dotnet", "TransactionService.dll"]
    ports:
      - "5002:8080"

  consolidatedservice1:
    build:
      context: .
      dockerfile: ConsolidatedService/Dockerfile
    depends_on:
      - sqlserver
      - redis
    entrypoint: ["dotnet", "ConsolidatedService.dll"]
    ports:
      - "5003:8080"

  consolidatedservice2:
    build:
      context: .
      dockerfile: ConsolidatedService/Dockerfile
    depends_on:
      - sqlserver
      - redis
    entrypoint: ["dotnet", "ConsolidatedService.dll"]
    ports:
      - "5004:8080"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  # locust:
  #   build:
  #     context: .
  #     dockerfile: Locust/Dockerfile
  #   depends_on:
  #     - sqlserver
  #     - transactionservice1
  #     - transactionservice2
  #     - consolidatedservice1
  #     - consolidatedservice2
  #   ports:
  #     - "5006:8080"
  #   environment:
  #     - LOCUST_HOST=http://locust:8080
  #   volumes:
  #     - ./Locust:/app
  #   command: 'locust -f locustfile.py  --host=http://locust:8080   --web-port=8080'

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - transactionservice1
      - transactionservice2
      - consolidatedservice1
      - consolidatedservice2
